[build]
  command = "yarn run build"
  #functions = "netlify/functions"
  publish = "apps/frontend/.next"

# Global environment variables (available in all contexts)
[build.environment]
  # Add global environment variables here
